# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Reach
email: neal.xie@dentsu.com
description: A organization website for dentsu Media US Data Science team.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dentsu-media-us-data-science.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

search_enabled: true

search:
  rel_rul: true
  button: false

aux_links:
  "dentsu Media US Data Science Team on GitHub":
    - "//github.com/dentsu-Media-US-Data-Science"

aux_links_new_tab: false

heading_anchors: true

color_scheme: light

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 dentsu Media US Data Science Team."

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
